### ISSUE TITLE
country_id not retrievable from candy form page

### ISSUE THREAD

**Issue by lizfonseca** [lizfonseca/SweetTooth#1]
I created a form in the following paths:

`/categories/:id/candies/new`
`/countries/:id/candies/new`

The user can enter candy information, including the category and country a particular candy belongs to through the forms. The problem comes when filling out the form for countries, the form isn't able to grab a `category_id` from the parameters. The same problem happens when I'm trying to persist the `country_id` from the form under the categories branch.

**Comment by jkonowitch** [comment]
I'm not sure I understand the issue here. What story are you working on? Can you put a link to the code you are referring too?
